modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "nethermania"
version = "${file.jarVersion}"
displayName = "Nether Mania"
authors = "Astemir"
description = '''
Nether
'''
[[dependencies.nethermania]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nethermania]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nethermania]]
modId = "skillsapi"
mandatory = true
versionRange = "[1.3]"
ordering = "AFTER"
side = "BOTH"
